pipeline:
  clone:
    image: plugins/git
    tags: true

  test:
    image: python:3
    commands:
      - python setup.py test

  build:
    image: python 3
      - python setup.py bdist_wheel
      - python setup.py sdist
      - python setup.py sdist --formats=zip

  staging:
    image: shocki/drone-devpi
    server: http://192.168.0.40:3141/
    index: dietzi/staging
    username: dietzi
    password: dietzi
    when:
      branch: master

  release:
    image: shocki/drone-devpi
    server: http://192.168.0.40:3141/
    index: dietzi/stable
    username: dietzi
    password: dietzi
    when:
      event: tag
      status: success