
clone:
  clone:
    image: plugins/git
    tags: true

pipeline:

  test:
    image: python:3
    commands:
      - python setup.py test
    environment:
      - PIP_INDEX_URL=http://dietzi.ddns.net:3141/

  build:
    image: python 3
      - python setup.py bdist_wheel
      - python setup.py sdist
      - python setup.py sdist --formats=zip
    environment:
      - PIP_INDEX_URL=http://dietzi.ddns.net:3141/

  staging:
    image: shocki/drone-devpi
    server: http://dietzi.ddns.net:3141/
    index: dietzi/staging
    secrets:
     - source: devpi_password
       target: plugin_password
     - source: devpi_user
       target: plugin_username
    when:
      branch: master

  release:
    image: shocki/drone-devpi
    server: http://dietzi.ddns.net:3141/
    index: dietzi/stable
    secrets:
     - source: devpi_password
       target: plugin_password
     - source: devpi_user
       target: plugin_username
    when:
      event: tag
      status: success